/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as ApiIllustrateRouteImport } from './routes/api/illustrate'
import { Route as ApiNarrateRouteImport } from './routes/api/narrate'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiIllustrateRoute = ApiIllustrateRouteImport.update({
  id: '/api/illustrate',
  path: '/api/illustrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNarrateRoute = ApiNarrateRouteImport.update({
  id: '/api/narrate',
  path: '/api/narrate',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/reset-password': typeof ResetPasswordRoute
  '/watch': typeof WatchRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/api/illustrate': typeof ApiIllustrateRoute
  '/api/narrate': typeof ApiNarrateRoute
  '/s/$shareId': typeof SShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/reset-password': typeof ResetPasswordRoute
  '/watch': typeof WatchRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/api/illustrate': typeof ApiIllustrateRoute
  '/api/narrate': typeof ApiNarrateRoute
  '/s/$shareId': typeof SShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/reset-password': typeof ResetPasswordRoute
  '/watch': typeof WatchRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/api/illustrate': typeof ApiIllustrateRoute
  '/api/narrate': typeof ApiNarrateRoute
  '/s/$shareId': typeof SShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/build'
    | '/reset-password'
    | '/watch'
    | '/library'
    | '/api/illustrate'
    | '/api/narrate'
    | '/s/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/build'
    | '/reset-password'
    | '/watch'
    | '/library'
    | '/api/illustrate'
    | '/api/narrate'
    | '/s/$shareId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/build'
    | '/reset-password'
    | '/watch'
    | '/_authenticated/library'
    | '/api/illustrate'
    | '/api/narrate'
    | '/s/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WatchRoute: typeof WatchRoute
  ApiIllustrateRoute: typeof ApiIllustrateRoute
  ApiNarrateRoute: typeof ApiNarrateRoute
  SShareIdRoute: typeof SShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/illustrate': {
      id: '/api/illustrate'
      path: '/api/illustrate'
      fullPath: '/api/illustrate'
      preLoaderRoute: typeof ApiIllustrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/narrate': {
      id: '/api/narrate'
      path: '/api/narrate'
      fullPath: '/api/narrate'
      preLoaderRoute: typeof ApiNarrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WatchRoute: WatchRoute,
  ApiIllustrateRoute: ApiIllustrateRoute,
  ApiNarrateRoute: ApiNarrateRoute,
  SShareIdRoute: SShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
